name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "
            cd /home/ec2-user &&
            
            if [ -d 'Horizon_Finance_backend' ]; then
              cd Horizon_Finance_backend &&
              git pull origin main;
            else
              git clone git@github.com:domcave/Horizon_Finance_backend.git &&
              cd Horizon_Finance_backend;
            fi
            
            # Run backend setup commands
            sudo systemctl stop nginx &&
            sudo systemctl stop horizon-finance-backend.service &&
            python3.11 -m venv venv &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            alembic revision --autogenerate &&
            alembic upgrade head &&
            sudo systemctl start nginx &&
            sudo systemctl restart horizon-finance-backend
          "
